version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: ["./gradlew", "bootRun"]

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: ["npm", "start"]
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

  postgres:
    ports:
      - "5432:5432"