version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
      - ./frontend/dist/frontend:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  postgres:
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: