spring:
  config:
    activate-on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:citizen_portal}?currentSchema=citizen_portal
    username: ${DB_USERNAME:citizen_admin}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate DDL as we use Liquibase
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true
        query:
          plan_cache_max_size: 64
          in_clause_parameter_padding: true
  liquibase:
    drop-first: false
    contexts: prod
    parameters:
      production: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24 hours
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 days
  file:
    upload-dir: ${FILE_UPLOAD_DIR:/var/uploads}
    max-file-size: 10MB
    allowed-extensions: .pdf,.jpg,.png,.jpeg
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.springframework.security: WARN
    com.example.citizenportal: INFO
    org.hibernate.SQL: WARN
  file:
    name: /var/log/citizen-portal/application.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30
      total-size-cap: 1GB
    time-based-rolling-policy:
      max-history: 60
      clean-history-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN