spring:
  config:
    activate-on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/citizen_portal_dev?currentSchema=citizen_portal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate DDL as we use Liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  liquibase:
    drop-first: false
    contexts: dev

app:
  jwt:
    secret: dev-secret-key-1234567890
    expiration-ms: 86400000 # 24 hours
    refresh-expiration-ms: 604800000 # 7 days
  file:
    upload-dir: ./uploads-dev
    max-file-size: 10MB
    allowed-extensions: .pdf,.jpg,.png,.jpeg,.doc,.docx

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.citizenportal: DEBUG
  file:
    name: ./logs/citizen-portal-dev.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7