spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: ${EMAIL_HOST:smtp.example.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
    contexts: ${LIQUIBASE_CONTEXTS:dev}
    default-schema: public
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    parameters:
      appSchema: citizen_portal

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000 # 24 hours
    refresh-expiration-ms: 604800000 # 7 days
  file:
    upload-dir: ${FILE_UPLOAD_DIR:uploads}
    max-file-size: 5MB
    allowed-extensions: .pdf,.jpg,.png,.jpeg
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:"http://localhost:4200,http://localhost:8080"}
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "*"
    exposed-headers: Authorization,Content-Disposition
    max-age: 3600
  security:
    password-strength: 8

server:
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true