spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: smtp.example.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000 # 24 hours
    refresh-expiration-ms: 604800000 # 7 days
  file:
    upload-dir: ${FILE_UPLOAD_DIR:uploads}
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"

server:
  servlet:
    context-path: /api
  error:
    include-message: always